/**
 * dados.js
 * 
 * Arquivo de dados da Rede Credenciada Oeste Saúde.
 * Expõe a variável global window.DADOS_COMPLETOS
 * que é consumida por DataManager na inicialização.
 * 
 * Se houver dados salvos no localStorage (chave 'oeste_prestadores_v2'),
 * eles terão prioridade sobre este arquivo.
 */

window.DADOS_COMPLETOS = {
    "prestadores": [
        {
            "nome": "CENTRO MEDICO DE ESPECIALIDADES PRES. PRUDENTE",
            "classificacao": "HOSPITAL",
            "tipo_codigo": "HOS",
            "especialidade": "CARDIOLOGIA, PEDIATRIA, GINECOLOGIA, ORTOPEDIA, NEUROLOGIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA FAGUNDES VARELLA, 185",
            "bairro": "VILA LESSA",
            "telefone": "(18) 3300-0100",
            "email": "contato@centromedico.com.br"
        },
        {
            "nome": "CLINICA MEDICA SANTA HELENA",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "CLINICA GERAL, DERMATOLOGIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "AV. BRASIL, 1500",
            "bairro": "CENTRO",
            "telefone": "(18) 3221-5555",
            "email": "santa.helena@clinica.com.br"
        },
        {
            "nome": "DR. GUILHERME MARTINS NANCI",
            "classificacao": "MEDICO",
            "tipo_codigo": "MED",
            "especialidade": "ORTOPEDIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA TIRADENTES, 800",
            "bairro": "CENTRO",
            "telefone": "(18) 3222-1111",
            "email": "guilherme.nanci@medico.com.br"
        },
        {
            "nome": "LABORATORIO ANALISES CLINICAS UNILAB",
            "classificacao": "LABORATORIO",
            "tipo_codigo": "LAB",
            "especialidade": "ANALISES CLINICAS, EXAMES LABORATORIAIS",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "AV. GETÚLIO VARGAS, 2000",
            "bairro": "CENTRO",
            "telefone": "(18) 3223-7777",
            "email": "contato@unilab.com.br"
        },
        {
            "nome": "HOSPITAL ESPERANCA",
            "classificacao": "HOSPITAL",
            "tipo_codigo": "HOS",
            "especialidade": "CLINICA GERAL, CIRURGIA GERAL, OBSTETRICA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA MARANHAO, 500",
            "bairro": "VILA MARCONDES",
            "telefone": "(18) 3225-9999",
            "email": "info@hospitalesperanca.com.br"
        },
        {
            "nome": "CLINICA TAMARA SILVA",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "PSICOLOGIA, PSIQUIATRIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA SANTA CRUZ, 300",
            "bairro": "CENTRO",
            "telefone": "(18) 3224-4444",
            "email": "tamara@clinicapsi.com.br"
        },
        {
            "nome": "DR. BRUNO FREITAS CERAVOLO",
            "classificacao": "MEDICO",
            "tipo_codigo": "MED",
            "especialidade": "MASTOLOGIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "AV. BRASIL, 2500",
            "bairro": "CENTRO",
            "telefone": "(18) 3226-2222",
            "email": "bruno.ceravolo@medico.com.br"
        },
        {
            "nome": "CENTRO DE DIAGNOSTICOS CADRI",
            "classificacao": "CENTRO DE DIAGNOSTICOS",
            "tipo_codigo": "CDI",
            "especialidade": "RADIOLOGIA, ULTRASSOM, TOMOGRAFIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA MATO GROSSO, 1200",
            "bairro": "CENTRO",
            "telefone": "(18) 3227-8888",
            "email": "cadri@diagnosticos.com.br"
        },
        {
            "nome": "DRA. BARBARA GONCALES OLIVO",
            "classificacao": "MEDICO",
            "tipo_codigo": "MED",
            "especialidade": "PNEUMOLOGIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA PARANA, 600",
            "bairro": "CENTRO",
            "telefone": "(18) 3228-3333",
            "email": "barbara.olivo@medico.com.br"
        },
        {
            "nome": "FISIOCLINICA S/S LTDA",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "FISIOTERAPIA, REABILITACAO",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "AV. WASHINGTON LUIS, 1800",
            "bairro": "CENTRO",
            "telefone": "(18) 3229-5555",
            "email": "contato@fisioclinica.com.br"
        },
        {
            "nome": "INSTITUTO DO RIM PRES. PRUDENTE",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "NEFROLOGIA, DIALISE",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA CEARA, 900",
            "bairro": "CENTRO",
            "telefone": "(18) 3230-1111",
            "email": "contato@institutodrim.com.br"
        },
        {
            "nome": "SANTA CASA MIS. PRES PRUDENTE",
            "classificacao": "HOSPITAL",
            "tipo_codigo": "HOS",
            "especialidade": "CLINICA GERAL, CIRURGIA, OBSTETRICA, PEDIATRIA",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA MINAS GERAIS, 1100",
            "bairro": "CENTRO",
            "telefone": "(18) 3231-6666",
            "email": "contato@santacasa.com.br"
        },
        {
            "nome": "CLINICA MEDICA DRACENA",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "CLINICA GERAL, CARDIOLOGIA",
            "cidade": "DRACENA",
            "endereco": "AV. BRASIL, 500",
            "bairro": "CENTRO",
            "telefone": "(18) 3271-2222",
            "email": "dracena@clinica.com.br"
        },
        {
            "nome": "HOSPITAL IAMADA PRES. PRUDENTE",
            "classificacao": "HOSPITAL",
            "tipo_codigo": "HOS",
            "especialidade": "CLINICA GERAL, CIRURGIA GERAL",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA AMAZONAS, 1400",
            "bairro": "CENTRO",
            "telefone": "(18) 3232-9999",
            "email": "contato@hospitaliamada.com.br"
        },
        {
            "nome": "ESTAR BEM CLINICA DE PSICOLOGIA",
            "classificacao": "CLINICA",
            "tipo_codigo": "CLI",
            "especialidade": "PSICOLOGIA, TERAPIA OCUPACIONAL",
            "cidade": "PRESIDENTE PRUDENTE",
            "endereco": "RUA GOIAS, 700",
            "bairro": "CENTRO",
            "telefone": "(18) 3233-4444",
            "email": "contato@estarbem.com.br"
        }
        // Adicione mais prestadores conforme necessário
    ],
    "especialidades": [
        "ALERGOLOGIA",
        "ANALISES CLINICAS",
        "CARDIOLOGIA",
        "CIRURGIA GERAL",
        "CIRURGIA PLASTICA",
        "CLINICA GERAL",
        "DERMATOLOGIA",
        "DIALISE",
        "ENDOCRINOLOGIA",
        "EXAMES LABORATORIAIS",
        "FISIOTERAPIA",
        "FONOAUDIOLOGIA",
        "GASTROENTEROLOGIA",
        "GERIATRIA",
        "GINECOLOGIA",
        "MASTOLOGIA",
        "NEFROLOGIA",
        "NEUROLOGIA",
        "NEUROCIRURGIA",
        "NUTRICAO",
        "OBSTETRICA",
        "OFTALMOLOGIA",
        "ONCOLOGIA",
        "ORTOPEDIA",
        "OTORRINOLARINGOLOGIA",
        "PEDIATRIA",
        "PNEUMOLOGIA",
        "PROCTOLOGIA",
        "PSICOLOGIA",
        "PSIQUIATRIA",
        "RADIOLOGIA",
        "REABILITACAO",
        "REUMATOLOGIA",
        "TERAPIA OCUPACIONAL",
        "TOMOGRAFIA",
        "ULTRASSOM",
        "UROLOGIA",
        "VASCULAR"
    ],
    "cidades": [
        "ADAMANTINA",
        "ALFREDO MARCONDES",
        "ALVARES MACHADO",
        "ANHUMAS",
        "AQUIDAUANA",
        "ARACATUBA",
        "ASSIS",
        "BATAGUASSU",
        "BIRIGUI",
        "CAIABU",
        "CAIUA",
        "CAMPO GRANDE",
        "CASSILANDIA",
        "CHAPADAO DO SUL",
        "CORUMBA",
        "COXIM",
        "DRACENA",
        "DOURADOS",
        "EMILIANOPOLIS",
        "ESTRELA DO NORTE",
        "EUCLIDES DA CUNHA PAULISTA",
        "FERNANDOPOLIS",
        "FLORIDA PAULISTA",
        "GUARARAPES",
        "IEPE",
        "INDIANA",
        "INUBIA PAULISTA",
        "IVINHEMA",
        "JALES",
        "JOAO RAMALHO",
        "JUNQUEIROPOLIS",
        "LUCELIA",
        "MARAPOAMA",
        "MARTINOPOLIS",
        "MIRANTE DO PARANAPANEMA",
        "MIRASSOL",
        "NANTES",
        "NARANDIBA",
        "NAVIRAI",
        "NOVA ANDRADINA",
        "OSVALDO CRUZ",
        "PACAEMBU",
        "PANORAMA",
        "PARAPUA",
        "PARANAIBA",
        "PENAPOLIS",
        "PIRAPOZINHO",
        "PONTA PORA",
        "PRESIDENTE BERNARDES",
        "PRESIDENTE EPITACIO",
        "PRESIDENTE PRUDENTE",
        "PRESIDENTE VENCESLAU",
        "QUATA",
        "RANCHARIA",
        "REGENTE FEIJO",
        "RIBEIRAO DOS INDIOS",
        "RINOPOLIS",
        "ROSANA",
        "SANDOVALINA",
        "SANTA FE DO SUL",
        "SAO JOSE DO RIO PRETO",
        "TEODORO SAMPAIO",
        "TRES LAGOAS",
        "TUPI PAULISTA",
        "VOTUPORANGA"
    ],
    "tipos": [
        "CENTRO DE DIAGNOSTICOS",
        "CLINICA",
        "FONOAUDIOLOGO",
        "HOSPITAL",
        "HOSPITAL DIA",
        "HOSPITAL MATERNIDADE",
        "LABORATORIO",
        "MEDICO",
        "NUTRICIONISTA",
        "PROFISSIONAL DE SAUDE"
    ]
};